(function(g){var window=this;'use strict';var Ifb=function(a){g.T.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.Tf=!1;this.player=a;this.S(a,"onStateChange",this.FO);this.S(a,"videodatachange",this.kp);this.S(a,"onInlinePreviewModeChange",this.h3);this.hf=new g.Xn(this.wv,null,this);g.D(this,this.hf)},a6=function(a){g.FR.call(this,a);
this.j=new Ifb(this.player);g.D(this,this.j);this.j.hide();g.VQ(this.player,this.j.element,4);if(a.isInline()){this.load();var b=a.getRootNode();g.io(b,["ytp-inline-preview-mode","ytp-no-contextmenu"]);this.player.T().K("web_rounded_containers")&&g.lo(a.getRootNode(),"ytp-rounded-inline-preview",!0);this.player.T().K("web_inline_player_disable_scrubbing")&&g.lo(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0)}};
g.v(Ifb,g.T);g.k=Ifb.prototype;
g.k.GL=function(){this.tooltip=new g.AV(this.player,this);g.D(this,this.tooltip);g.VQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Oc=new g.zS(this.player);g.D(this,this.Oc);var a=["ytp-inline-preview-scrim"];this.player.T().K("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.jj=new g.T({G:"div",Ja:a});g.D(this,this.jj);this.jj.Da(this.element);this.S(this.jj.element,"click",this.uG);this.player.T().K("web_inline_player_expand_to_watch")&&(a=new g.B2(this.player,
this),g.D(this,a),a.Da(this.jj.element));this.mj=new g.tV(this.player,this,300);g.D(this,this.mj);this.mj.Da(this.jj.element);this.controls=new g.T({G:"div",N:"ytp-inline-preview-controls"});g.D(this,this.controls);this.controls.Da(this.element);a=new g.cU(this.player,this,this.player.T().K("kevlar_simp_remove_min_width_for_mute_button"));g.D(this,a);a.Da(this.controls.element);a=new g.rV(this.player,this);g.D(this,a);a.Da(this.controls.element);this.Ic=new g.rU(this.player,this);g.D(this,this.Ic);
g.VQ(this.player,this.Ic.element,4);this.S(this.player,"appresize",this.Db);this.S(this.player,"fullscreentoggled",this.Db);this.Db()};
g.k.show=function(){g.Yn(this.hf);this.Tf||(this.GL(),this.Tf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Ic.show()};
g.k.hide=function(){this.hf.stop();g.T.prototype.hide.call(this);this.player.isInline()||this.Tf&&this.Ic.hide()};
g.k.ra=function(){g.T.prototype.ra.call(this)};
g.k.uG=function(a){a.target!==this.jj.element||this.player.T().K("web_inline_player_expand_to_watch")||this.player.Na("onExpandInlinePreview",a)};
g.k.h3=function(){g.lo(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ie=function(){this.Ic.xc();this.mj.xc()};
g.k.wv=function(){this.Ie();g.Yn(this.hf)};
g.k.Db=function(){g.KU(this.Ic,0,this.player.gb().getPlayerSize().width,!1);g.uU(this.Ic)};
g.k.FO=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.kp=function(a,b){if(this.player.isInline()&&(g.lo(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.lI),this.player.K("web_player_disable_inline_scrubbing")||this.player.K("disable_inline_preview_scrubbing_for_vac_ads_on_web"))){var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.lo(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Bc=function(){return this.tooltip};
g.k.jg=function(){return!1};
g.k.gh=function(){return!1};
g.k.xd=function(){return!1};
g.k.Hl=function(){return!1};
g.k.lD=function(){};
g.k.Jp=function(){};
g.k.Nx=function(){};
g.k.Gm=function(){return null};
g.k.iF=function(){return null};
g.k.AB=function(){return null};
g.k.rk=function(){return new g.nl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Hv=function(a,b,c,d,e){var f=d=0,h=0,l=g.Gl(a);if(b){c=g.go(b,"ytp-miniplayer-expand-watch-page-button");var m=g.go(b,"ytp-mute-button"),n=g.go(b,"ytp-subtitles-button"),p=g.zl(b,this.element);b=g.Gl(b);d=p.y+40;c&&(h=8);if(n||m)h=p.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.gb().getPlayerSize().width;h=g.Td(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.gp=function(){};
g.k.Cl=function(){return!1};
g.k.mD=function(){};
g.k.pz=function(){};
g.k.Nq=function(){};
g.k.Mq=function(){};
g.k.rE=function(){};
g.k.Lr=function(){};g.v(a6,g.FR);a6.prototype.Lk=function(){return!1};
a6.prototype.load=function(){this.player.hideControls();this.j.show()};
a6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.ER("inline_preview",a6);})(_yt_player);
