(function(g){var window=this;'use strict';var Rfb=function(a){g.T.call(this,{G:"div",N:"ytp-miniplayer-ui"});this.Tf=!1;this.player=a;this.S(a,"minimized",this.Uh);this.S(a,"onStateChange",this.FO)},Sfb=function(a){g.FR.call(this,a);
this.u=new g.YF(this);this.j=new Rfb(this.player);this.j.hide();g.VQ(this.player,this.j.element,4);a.og()&&(this.load(),g.lo(a.getRootNode(),"ytp-player-minimized",!0));this.player.K("web_rounded_containers")&&g.lo(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.v(Rfb,g.T);g.k=Rfb.prototype;
g.k.GL=function(){this.tooltip=new g.AV(this.player,this);g.D(this,this.tooltip);g.VQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Oc=new g.zS(this.player);g.D(this,this.Oc);this.jj=new g.T({G:"div",N:"ytp-miniplayer-scrim"});g.D(this,this.jj);this.jj.Da(this.element);this.S(this.jj.element,"click",this.uG);var a=new g.T({G:"button",Ja:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.RN()]});g.D(this,a);a.Da(this.jj.element);this.S(a.element,"click",this.So);
a=new g.B2(this.player,this);g.D(this,a);a.Da(this.jj.element);this.yu=new g.T({G:"div",N:"ytp-miniplayer-controls"});g.D(this,this.yu);this.yu.Da(this.jj.element);this.S(this.yu.element,"click",this.uG);var b=new g.T({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,b);b.Da(this.yu.element);a=new g.T({G:"div",N:"ytp-miniplayer-play-button-container"});g.D(this,a);a.Da(this.yu.element);var c=new g.T({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,c);c.Da(this.yu.element);this.dW=new g.gU(this.player,
this,!1);g.D(this,this.dW);this.dW.Da(b.element);b=new g.eU(this.player,this);g.D(this,b);b.Da(a.element);this.nextButton=new g.gU(this.player,this,!0);g.D(this,this.nextButton);this.nextButton.Da(c.element);this.mj=new g.tV(this.player,this);g.D(this,this.mj);this.mj.Da(this.jj.element);this.Ic=new g.rU(this.player,this);g.D(this,this.Ic);g.VQ(this.player,this.Ic.element,4);this.kG=new g.T({G:"div",N:"ytp-miniplayer-buttons"});g.D(this,this.kG);g.VQ(this.player,this.kG.element,4);a=new g.T({G:"button",
Ja:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.RN()]});g.D(this,a);a.Da(this.kG.element);this.S(a.element,"click",this.So);a=new g.T({G:"button",Ja:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},W:[g.YN()]});g.D(this,a);a.Da(this.kG.element);this.S(a.element,"click",this.Z5);this.S(this.player,"presentingplayerstatechange",this.td);this.S(this.player,"appresize",this.Db);this.S(this.player,"fullscreentoggled",this.Db);this.Db()};
g.k.show=function(){this.hf=new g.Xn(this.wv,null,this);this.hf.start();this.Tf||(this.GL(),this.Tf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Ic.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.hf&&(this.hf.dispose(),this.hf=void 0);g.T.prototype.hide.call(this);this.player.og()||(this.Tf&&this.Ic.hide(),this.player.loadModule("annotations_module"))};
g.k.ra=function(){this.hf&&(this.hf.dispose(),this.hf=void 0);g.T.prototype.ra.call(this)};
g.k.So=function(){this.player.stopVideo();this.player.Na("onCloseMiniplayer")};
g.k.Z5=function(){this.player.playVideo()};
g.k.uG=function(a){if(a.target===this.jj.element||a.target===this.yu.element)g.zM(this.player.Fb())?this.player.pauseVideo():this.player.playVideo()};
g.k.Uh=function(){g.lo(this.player.getRootNode(),"ytp-player-minimized",this.player.og())};
g.k.Ie=function(){this.Ic.xc();this.mj.xc()};
g.k.wv=function(){this.Ie();this.hf&&this.hf.start()};
g.k.td=function(a){g.S(a.state,32)&&this.tooltip.hide()};
g.k.Db=function(){g.KU(this.Ic,0,this.player.gb().getPlayerSize().width,!1);g.uU(this.Ic)};
g.k.FO=function(a){this.player.og()&&(0===a?this.hide():this.show())};
g.k.Bc=function(){return this.tooltip};
g.k.jg=function(){return!1};
g.k.gh=function(){return!1};
g.k.xd=function(){return!1};
g.k.Hl=function(){return!1};
g.k.lD=function(){};
g.k.Jp=function(){};
g.k.Nx=function(){};
g.k.Gm=function(){return null};
g.k.iF=function(){return null};
g.k.AB=function(){return null};
g.k.rk=function(){return new g.nl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Hv=function(a,b,c,d,e){var f=0,h=d=0,l=g.Gl(a);if(b){c=g.go(b,"ytp-prev-button")||g.go(b,"ytp-next-button");var m=g.go(b,"ytp-play-button"),n=g.go(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.zl(b,this.element),h=b.x,f=b.y-12):n&&(h=g.go(b,"ytp-miniplayer-button-top-left"),f=g.zl(b,this.element),b=g.Gl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.gb().getPlayerSize().width;e=f+(e||0);l=g.Td(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.gp=function(){};
g.k.Cl=function(){return!1};
g.k.mD=function(){};
g.k.pz=function(){};
g.k.Nq=function(){};
g.k.Mq=function(){};
g.k.rE=function(){};
g.k.Lr=function(){};g.v(Sfb,g.FR);g.k=Sfb.prototype;g.k.onVideoDataChange=function(){if(this.player.K("web_rounded_containers")&&this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9,c=a>b+.1;g.gw("enable_no_border_vertical_videos_killswitch")?g.lo(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",c):(a=c||a<b-.1,g.lo(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a))}};
g.k.create=function(){g.FR.prototype.create.call(this);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Lk=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.ER("miniplayer",Sfb);})(_yt_player);
